/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: shojig (https://sketchfab.com/shojig)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/limbic-system-ap-psychology-042b7c37263f4309bc8b4e18dc989102
Title: Limbic System - AP Psychology
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={3.782}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.mesh0.geometry} material={materials.mat0_50} />
            <mesh geometry={nodes.mesh1.geometry} material={materials.mat0_49} />
            <mesh geometry={nodes.mesh2.geometry} material={materials.mat0_48} />
            <mesh geometry={nodes.mesh3.geometry} material={materials.mat0_47} />
            <mesh geometry={nodes.mesh4.geometry} material={materials.material_7} />
            <mesh geometry={nodes.mesh5.geometry} material={materials.material_6} />
            <mesh geometry={nodes.mesh6.geometry} material={materials.material_5} />
            <mesh geometry={nodes.mesh7.geometry} material={materials.material_4} />
            <mesh geometry={nodes.mesh10.geometry} material={materials.mat0_44} />
            <mesh geometry={nodes.mesh11.geometry} material={materials.mat0_43} />
            <mesh geometry={nodes.mesh12.geometry} material={materials.mat0_42} />
            <mesh geometry={nodes.mesh13.geometry} material={materials.mat0_41} />
            <mesh geometry={nodes.mesh14.geometry} material={materials.mat0_40} />
            <mesh geometry={nodes.mesh15.geometry} material={materials.mat0_39} />
            <mesh geometry={nodes.mesh16.geometry} material={materials.mat0_38} />
            <mesh geometry={nodes.mesh17.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh18.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh19.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh20.geometry} material={materials.mat0_37} />
            <mesh geometry={nodes.mesh21.geometry} material={materials.mat0_36} />
            <mesh geometry={nodes.mesh22.geometry} material={materials.mat0_35} />
            <mesh geometry={nodes.mesh23.geometry} material={materials.mat0_34} />
            <mesh geometry={nodes.mesh24.geometry} material={materials.mat0_33} />
            <mesh geometry={nodes.mesh25.geometry} material={materials.mat0_33} />
            <mesh geometry={nodes.mesh26.geometry} material={materials.mat0_33} />
            <mesh geometry={nodes.mesh27.geometry} material={materials.mat0_32} />
            <mesh geometry={nodes.mesh28.geometry} material={materials.mat0_31} />
            <mesh geometry={nodes.mesh29.geometry} material={materials.mat0_30} />
            <mesh geometry={nodes.mesh30.geometry} material={materials.mat0_28} />
            <mesh geometry={nodes.mesh31.geometry} material={materials.mat0_27} />
            <mesh geometry={nodes.mesh32.geometry} material={materials.mat0_26} />
            <mesh geometry={nodes.mesh33.geometry} material={materials.mat0_25} />
            <mesh geometry={nodes.mesh34.geometry} material={materials.mat0_24} />
            <mesh geometry={nodes.mesh39.geometry} material={materials.mat0_19} />
            <mesh geometry={nodes.mesh40.geometry} material={materials.mat0_18} />
            <mesh geometry={nodes.mesh41.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh42.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh43.geometry} material={materials.material_3} />
            <mesh geometry={nodes.mesh44.geometry} material={materials.mat0_17} />
            <mesh geometry={nodes.mesh45.geometry} material={materials.mat0_16} />
            <mesh geometry={nodes.mesh46.geometry} material={materials.mat0_15} />
            <mesh geometry={nodes.mesh47.geometry} material={materials.mat0_14} />
            <mesh geometry={nodes.mesh48.geometry} material={materials.mat0_29} />
            <mesh geometry={nodes.mesh49.geometry} material={materials.mat0_13} />
            <mesh geometry={nodes.mesh50.geometry} material={materials.material_1} />
            <mesh geometry={nodes.mesh51.geometry} material={materials.material_0} />
            <mesh geometry={nodes.mesh58.geometry} material={materials.mat0_6} />
            <mesh geometry={nodes.mesh59.geometry} material={materials.mat0_5} />
            <mesh geometry={nodes.mesh60.geometry} material={materials.mat0_4} />
            <mesh geometry={nodes.mesh61.geometry} material={materials.mat0_3} />
            <mesh geometry={nodes.mesh62.geometry} material={materials.mat0_2} />
            <mesh geometry={nodes.mesh63.geometry} material={materials.mat0_1} />
            <mesh geometry={nodes.mesh64.geometry} material={materials.mat0_0} />
            <mesh geometry={nodes.mesh65.geometry} material={materials.mat0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
